<?xml version="1.0" encoding="utf-8"?><Database Name="LanguageCenter" Class="LanguageCenterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProgramId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Room" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Class_ClassSchedule" Member="ClassSchedules" ThisKey="ClassId" OtherKey="ClassId" Type="ClassSchedule" />
      <Association Name="Class_Registration" Member="Registrations" ThisKey="ClassId" OtherKey="ClassId" Type="Registration" />
      <Association Name="Program_Class" Member="Program" ThisKey="ProgramId" OtherKey="ProgramId" Type="Program" IsForeignKey="true" />
      <Association Name="Teacher_Class" Member="Teacher" ThisKey="TeacherId" OtherKey="TeacherId" Type="Teacher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassSchedule" Member="ClassSchedules">
    <Type Name="ClassSchedule">
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DayOfWeek" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="EndTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="Class_ClassSchedule" Member="Class" ThisKey="ClassId" OtherKey="ClassId" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Consultation" Member="Consultations">
    <Type Name="Consultation">
      <Column Name="ConsultationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactInfo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RequestStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Student_Consultation" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="PaymentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegistrationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentMethod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Registration_Payment" Member="Registration" ThisKey="RegistrationId" OtherKey="RegistrationId" Type="Registration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlacementTest" Member="PlacementTests">
    <Type Name="PlacementTest">
      <Column Name="PlacementTestId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TestTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="SuggestedLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResultScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Student_PlacementTest" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Program" Member="Programs">
    <Type Name="Program">
      <Column Name="ProgramId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LevelName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DurationMonths" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fee" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProgramImage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProgramStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Program_Class" Member="Classes" ThisKey="ProgramId" OtherKey="ProgramId" Type="Class" />
    </Type>
  </Table>
  <Table Name="dbo.Registration" Member="Registrations">
    <Type Name="Registration">
      <Column Name="RegistrationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Registration_Payment" Member="Payments" ThisKey="RegistrationId" OtherKey="RegistrationId" Type="Payment" />
      <Association Name="Class_Registration" Member="Class" ThisKey="ClassId" OtherKey="ClassId" Type="Class" IsForeignKey="true" />
      <Association Name="Student_Registration" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Student_Consultation" Member="Consultations" ThisKey="StudentId" OtherKey="StudentId" Type="Consultation" />
      <Association Name="Student_PlacementTest" Member="PlacementTests" ThisKey="StudentId" OtherKey="StudentId" Type="PlacementTest" />
      <Association Name="Student_Registration" Member="Registrations" ThisKey="StudentId" OtherKey="StudentId" Type="Registration" />
      <Association Name="UserAccount_Student" Member="UserAccount" ThisKey="UserId" OtherKey="UserId" Type="UserAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="TeacherId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Specialty" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ExperienceYears" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherImage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Teacher_Class" Member="Classes" ThisKey="TeacherId" OtherKey="TeacherId" Type="Class" />
      <Association Name="UserAccount_Teacher" Member="UserAccount" ThisKey="UserId" OtherKey="UserId" Type="UserAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAccount" Member="UserAccounts">
    <Type Name="UserAccount">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="UserAccount_Student" Member="Students" ThisKey="UserId" OtherKey="UserId" Type="Student" />
      <Association Name="UserAccount_Teacher" Member="Teachers" ThisKey="UserId" OtherKey="UserId" Type="Teacher" />
    </Type>
  </Table>
</Database>